import type {Attempt,Concept,Question} from './types';
export const normalizeAnswer=(value:string)=>value.normalize('NFKC').trim().toLocaleLowerCase('id-ID').replace(/[.!?;,]+$/g,'').replace(/\s+/g,' ');
export const gradeAnswer=(value:string,accepted:string[])=>accepted.some(answer=>normalizeAnswer(value)===normalizeAnswer(answer));
export function updateMastery(current:number,correct:boolean,recent:Attempt[]=[],difficulty=1){const recentWrong=recent.slice(-5).filter(a=>!a.correct).length;const delta=correct?(5+difficulty*2+Math.min(recentWrong,2)*2):-(7+difficulty*2);return Math.max(0,Math.min(100,Math.round(current+delta*(1-current/140))));}
export function nextReview(mastery:number,correct:boolean,now=new Date()){const days=!correct?0:mastery<31?1:mastery<61?3:mastery<81?7:18;const d=new Date(now);d.setDate(d.getDate()+days);return d.toISOString();}
export function selectAdaptiveQuestions(questions:Question[],concepts:Concept[],attempts:Attempt[],count=10){const seen=new Map<string,number>();attempts.forEach(a=>seen.set(a.questionId,(seen.get(a.questionId)||0)+1));const active=new Map(concepts.map(c=>[c.id,c]));const remaining=questions.filter(q=>active.has(q.conceptId)).map(q=>{const c=active.get(q.conceptId)!;const recent=attempts.slice(-20).filter(a=>a.conceptId===q.conceptId);const mistake=recent.some(a=>!a.correct)?32:0;const recovery=recent.length&&recent.at(-1)?.correct===false?18:0;const seenCount=seen.get(q.id)||0;const novelty=seenCount===0?24:0;const repetitionPenalty=seenCount*35;const weakness=100-c.mastery;const flow=c.mastery>65?8:0;return{q,score:weakness*.5+mistake+recovery+novelty+flow-repetitionPenalty+Math.random()*16}}).sort((a,b)=>b.score-a.score);const selected:Question[]=[];while(remaining.length&&selected.length<count){const previous=selected.at(-1)?.conceptId;let pick=remaining.findIndex(item=>item.q.conceptId!==previous);if(pick<0)pick=0;selected.push(remaining.splice(pick,1)[0].q)}return selected;}

export function shuffleQuestionChoices(question:Question,random=Math.random):Question{const choices=[...question.choices];for(let i=choices.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]]}return{...question,choices}}
export function mergeConcept(existing:Concept[],candidate:Concept){const key=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'_');const match=existing.find(c=>c.id===candidate.id||key(c.title)===key(candidate.title));if(!match)return [...existing,candidate];return existing.map(c=>c.id===match.id?{...c,sources:[...new Set([...c.sources,...candidate.sources])],examples:[...new Set([...c.examples,...candidate.examples])],mastery:c.mastery}:c);}
export const scoreAttempt=(correct:boolean,difficulty:number,recovered:boolean,streak:number)=>correct?10+difficulty*5+(recovered?20:0)+(streak>0&&streak%5===0?10:0):0;
